# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pena, WTF?
email:
description: >- # this means to ignore newlines until "baseurl:" 
  shaman says yaman<br>
  the bestiest site in the multiverse<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pena.wtf" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-161776959-1
twitter_username: _penatrix
github_username:  gingerdeer
date_format: "%B %-d, %Y"
mathjax: true # MathJax equations, e.g. true
logo: lines.png

# Build settings
markdown: kramdown
remote_theme: mmistakes/so-simple-theme
plugins:
  - jekyll-feed

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: true

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/
  music:
    output: true
    permalink: /:collection/:path/
  math:
    output: true
    permalink: /:collection/:path/
  code:
    output: true
    permalink: /:collection/:path/
  katalikko:
    output: true
    permalink: /:collection/:path/
  other:
    output: true
    permalink: /:collection/:path/


# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_music"
      type: music
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_math"
      type: math
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_code"
      type: code
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_katalikko"
      type: katalikko
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_other"
      type: other
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: shaman
  picture: /images/yaman.png
  email:
  twitter:
  links:
    - title: GitHub
      url: https://github.com/gingerdeer
      icon: fab fa-github-square
    - title: LinkedIn
      url: https://www.linkedin.com/in/pentti-sunila-a967a1123/
      icon: fab fa-linkedin
    - title: SoundCloud
      url: https://soundcloud.com/gidetrix
      icon: fab fa-soundcloud

# Footer Links
footer_links:
  - title: GitHub
    url: https://github.com/gingerdeer
    icon: fab fa-github-square
  - title: LinkedIn
    url: https://www.linkedin.com/in/pentti-sunila-a967a1123/
    icon: fab fa-linkedin
  - title: SoundCloud
    url: https://soundcloud.com/gidetrix
    icon: fab fa-soundcloud
  - title: Bandcamp
    url: https://dream-lands.bandcamp.com/
    icon: fab fa-bandcamp
  - title: Twitter
    url: https://twitter.com/_penatrix
    icon: fab fa-twitter
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
